### ISSUE TITLE
SNOWTAM ATIS issues

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#352]
All reported to ATIS dev, posting it here for others awareness

- Does not acually check if ICAO provided matches with ATIS airport
- Caution slippery twy/exits is triggered regardless of runway state?
- RCR text is in caps, but rest of ATIS is not. The feature to turn all text to upper/lowercase results in ATIS generation errors.
- If two parts matches, it should say "FIRST AND SECOND PART" instead of repeating the same information as two separate entries

**Comment by Sanderli25** [comment]
When sitting ENGM, SNOWTAM feature only works when using combined ATIS. When changing to Arr & Dep ATIS, the maker URL does not contain the SNOWTAM parts.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/5b0c9fa9-ce67-4567-8b70-e33df6ad508d)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/673a4e18-b258-402f-af2f-653ddb4b7c46)

**Comment by Sanderli25** [comment]
When using SPO or SRO, ATIS should not give RCR for both runways as shown below - only for the respective runway:
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/9be393ea-5007-4e5f-a265-5b9dd7cfbdd8)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/64000949-dd22-4133-98fc-3a9e03ad0891)

**Comment by Adrian2k** [comment]
> When using SPO or SRO, ATIS should not give RCR for both runways as shown below - only for the respective runway

forwarded to dev

**Comment by Sanderli25** [comment]
Snowtam for ENGM (IPPC.no) will reagardless of runawy in use show for RWY 01L and 01R.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/3dd9f636-e77e-4673-ad59-15533151ebed)

When runway 19R and 19L is in use as now, the RCR should change so that 01R says for 19L and 01L to 19R.

Looking at the real ATIS, it should say RCR for the active runway. The RCR time "0834" matches the one from the briefing, and the values are the same.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/7b95249a-c3f3-4ba7-b864-6a916b5dd02d)

How the ATIS is generated now:
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/2485d1d1-28de-489c-808e-c64298a3a7e5)

**Comment by marud94** [comment]
> Snowtam for ENGM (IPPC.no) will reagardless of runawy in use show for RWY 01L and 01R.
> 
> ![image](https://private-user-images.githubusercontent.com/89723211/318189642-3dd9f636-e77e-4673-ad59-15533151ebed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjI4NzAsIm5iZiI6MTczMzU2MjU3MCwicGF0aCI6Ii84OTcyMzIxMS8zMTgxODk2NDItM2RkOWY2MzYtZTc3ZS00NjczLWFkNTktMTU1MzMxNTFlYmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA5MDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNzNhOWE0YjA0ODFiMmU5MWY4MWMyN2JkZTJmYWQ5NGYwYzViYjE5NDdlN2NmNWNiZmM4ZjVkZjdkMjU2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.slmJ_O7AecI-M26KN57pRFRjJET9X7xREsDIIKnS9PM)
> 
> When runway 19R and 19L is in use as now, the RCR should change so that 01R says for 19L and 01L to 19R.
> 
> Looking at the real ATIS, it should say RCR for the active runway. The RCR time "0834" matches the one from the briefing, and the values are the same.
> 
> ![image](https://private-user-images.githubusercontent.com/89723211/318189816-7b95249a-c3f3-4ba7-b864-6a916b5dd02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjI4NzAsIm5iZiI6MTczMzU2MjU3MCwicGF0aCI6Ii84OTcyMzIxMS8zMTgxODk4MTYtN2I5NTI0OWEtYzNmMy00YmE3LWI4NjQtNmE5MTZiNWRkMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA5MDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NmJjMmU0YTc5ODdmMDQ5ZmRmOWUyYjliNzU1ZjgzNzIyYmI0YTkyNTdhNDY0MjhlMGNjYjYxMTA2NGNkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-56tBs7YudgfvVPwbgnfsu2k3_Xc44ptsDtBR1rLggo)
> 
> How the ATIS is generated now: ![image](https://private-user-images.githubusercontent.com/89723211/318189923-2485d1d1-28de-489c-808e-c64298a3a7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjI4NzAsIm5iZiI6MTczMzU2MjU3MCwicGF0aCI6Ii84OTcyMzIxMS8zMTgxODk5MjMtMjQ4NWQxZDEtMjhkZS00ODljLTgwOGUtYzY0Mjk4YTNhN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA5MDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNzZhOWUwYzk1NzQyYzcwZTA2MjVkYmQxNWJlNTRhNGMzNmE0OGM4Yjg3NjBhMzM2YTAyNTMwZDMwOWFmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LutHlXLJ7zrsGoV08Got0yV0M7r8LiQ6jvPw_c88s3A)

@Sanderli25 
Dev has implemented (and deployed) a update that will check for runway in use and state the runway name for RCRs. This means that 01L will automatically be 19R on the report if 19s in use. It will also check for runway in use and only report the snowtam on the correct atis for the runway. This means that if 19L is dep and 19R is arr, RCR for 19L is only on the dep atis and 19R is only on arr atis.

Please test and fiddle with the snowtam features a bit and report any findings, good or bad. Im currently unable due to family emergency.

**Comment by marud94** [comment]
This is tested and found to be working for the most part. Minor bugs when using on ENGM with SPO and DEP and ARR atises. Reported to dev. Closing this issue as the feature is added.
