### ISSUE TITLE
Add GM visual points - STAR list

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#404]
Recommend adding COZIP, YOMME, MIDWO, EXLOF to "Assign STAR" list as "VISUAL"

Flesland has it, but not Gardermoen:
![image](https://github.com/user-attachments/assets/4bf59fed-47c9-461d-941e-822274f659e5)

**Comment by Adrian2k** [comment]
It is quite a wonky setup for ENBR where I had to have specific names for each runway (17 = VISUAL & 35 = VISAPP), since they had to be added as STARs instead of APPs - due to GNG not supporting visual as an approach type.

![image](https://github.com/user-attachments/assets/affbd3a3-d378-4428-8602-6489f4c5d5a0)

**Comment by Sanderli25** [comment]
This looked good when I tested it.
