### ISSUE TITLE
Pull NOTAM data on startup

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#428]
Looks to be possible to pull data on logon to the Airspace Management list, without having to open the NOTAM list in Topsky. In the Norwegian sectorfile, we have to do it to let AMS know what airspace is activated by NOTAM.

Is it possible to have a look and see if we can pull NOTAM data immediately after connection to Airspace management list?

**Comment by morettio** [comment]
Have you seen it in other countries sectorfile? This has been a topic for plugin dev, but I haven't seen it added to the plugin.

**Comment by krislarsen** [comment]
> Have you seen it in other countries sectorfile? This has been a topic for plugin dev, but I haven't seen it added to the plugin.

This has been observed in the Danish sectorfile

**Comment by morettio** [comment]
I'll have a look at the Danish sectorfile.

**Comment by morettio** [comment]
It seems like areas in EKDK are added to https://lara.vatsim.pt/api/areas/EK/.
I need to talk to EKDK sectorfile dep to understand more.

**Comment by morettio** [comment]
Lara.vatsim is not a solution, it's not maintained anymore.
The EKDK notam is pulled on startup because the AMC window is visible on startup.

**Comment by morettio** [comment]
A solution would be to add "Window_ASM=1,1500,1000" to your TopSkySettingsLocal.txt file. Where "1500" is the horizontal placement and "1000" is the vertical placement on your screen.
@krislarsen

**Comment by morettio** [comment]
Topsky can since the last update pull AUP data, but sadly Norway is not part of the European EAUP (_The European Airspace Use Plan_). ESOS, EFIN and EKDK are a part of and can pull from eurocontroll EAUP info. We can only pull from NOTAM and pr now we need to open the AMC window to activate the pull of NOTAM data.

I will close this issue, but if there is any change or more info we can open it again.
