### ISSUE TITLE
A380 alias

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#479]
Something to send pilots flying A380 in/out of incapable airports

**Suggestions:**
Hello. (ADEP) is not a suitable airport for an A380. Please either select an more suitable aircraft or airport to operate from.

Hello. (ADES) is not a suitable airport for an A380 and we can not accommodate you there. It is suggested we divert you to another airport, for example ENGM.

@DotWallop is the wording suitable?

**Comment by DotWallop** [comment]
> Hello. (ADEP) is not a suitable airport for an A380. Please either select an more suitable aircraft or airport to operate from.

We are quite weary not to be too "demanding" in this sense.

I suggest:

Hello. (ADEP) is not a suitable airport for an A380. I highly suggest either selecting an more suitable aircraft or airport to operate from.

**Comment by marud94** [comment]
Added:
`.dca380 .msg $aircraft $dep is not a suitable airport for your aircraft type. Confirm you know all the restricitions and limitations followed by departing from $dep?
.aca380 .msg $aircraft $arr is not a suitable airport for your aircraft type. Confirm you know all the restricitions and limitations followed by departing from $arr?
.dnoa380 .msg $aircraft $dep is not a suitable airport for your aircraft type. I highly suggest either selecting a more suitable aircraft or airport to operate from.
.anoa380 .msg $aircraft $arr is not a suitable airport for your aircraft type. I highly suggest either selecting a more suitable aircraft or airport to operate from.`

and:
`.supda380 Callsign $1 is insisting on flying from $dep which is unable to handle his aircraft type due to size and performance.
.supaa380 Callsign $1 is insisting on flying to $arr which is unable to handle his aircraft type due to size and performance.`
